# Generated by Django 4.2.9 on 2025-11-16 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_appsettings_ride_current_cost_ride_fare_boosts'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_telegram_id', models.CharField(max_length=100)),
                ('message_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.ride')),
            ],
            options={
                'db_table': 'ride_notifications',
                'indexes': [models.Index(fields=['ride', 'driver_telegram_id'], name='ride_notifi_ride_id_209c15_idx')],
                'unique_together': {('ride', 'driver_telegram_id')},
            },
        ),
    ]
